# Generated by Django 4.2.14 on 2024-07-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=1234, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=13456)),
            ],
        ),
    ]
