# Generated by Django 4.2.14 on 2024-07-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1234)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=13456)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
