# Generated by Django 4.2.14 on 2024-08-04 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_apis', '0002_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_elections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_apis.users')),
                ('candidates', models.ManyToManyField(related_name='create_election', to='login_apis.users')),
            ],
        ),
    ]
