# Generated by Django 4.2.14 on 2024-08-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_apis', '0003_candiates_create_elections'),
    ]

    operations = [
        migrations.DeleteModel(
            name='candiates',
        ),
        migrations.DeleteModel(
            name='create_elections',
        ),
    ]
