# Generated by Django 4.2.14 on 2024-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_apis', '0003_create_elections'),
    ]

    operations = [
        migrations.CreateModel(
            name='candiates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12345678)),
                ('postion', models.CharField(max_length=1234356478)),
            ],
        ),
        migrations.RenameField(
            model_name='create_elections',
            old_name='admin',
            new_name='organizer',
        ),
        migrations.RemoveField(
            model_name='create_elections',
            name='candidates',
        ),
        migrations.AddField(
            model_name='create_elections',
            name='number_of_candidates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='create_elections',
            name='title',
            field=models.CharField(default='', max_length=12345678),
        ),
    ]
