# Generated by Django 4.2.14 on 2024-08-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_election_creation', '0002_candiates_number_of_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candiates',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candiates',
            name='number_of_votes',
        ),
        migrations.RemoveField(
            model_name='candiates',
            name='postion',
        ),
    ]
