# Generated by Django 4.2.14 on 2024-08-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_election_creation', '0003_remove_candiates_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candiates',
            name='postion',
            field=models.CharField(default=12, max_length=1234356478),
        ),
    ]
