# Generated by Django 4.2.14 on 2024-08-06 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_election_creation', '0004_candiates_postion'),
    ]

    operations = [
        migrations.AddField(
            model_name='candiates',
            name='belong_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_election_creation.create_elections'),
        ),
        migrations.AddField(
            model_name='candiates',
            name='name',
            field=models.CharField(default='None', max_length=12345678),
        ),
        migrations.AddField(
            model_name='candiates',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
